### ISSUE TITLE
evaluate function doesn't work with entrypoint parameter. 

### ISSUE THREAD

**Issue by rai-prashanna** [sangkeon/java-opa-wasm#5]
OPA version used == 0.52.0
I optimized rego file using -O=1 flag which generated new rego file. 
After that  i generated, wasm binary using build -t wasm flag. 
when i try to evaluate json with wasm compile binary using java-opa-wasm library.
It doesn't work with following methods. 
public String evaluate(String json, String entrypoint) or  public String evaluate(String json, int entrypoint) 
But, it works with public String evaluate(String json) only. 
In my case rego contains multiple entrypoints. 
Any help will be appreciated!
Thanks!

**Comment by sangkeon** [comment]
Please call loadEntrypoints() prior to call String evaluate(String json, String entrypoint) and check it works.
If it works, call loadEntrypoints() prior to call evaluate(json, entrypoint) until I will fix this until next release.

**Comment by rai-prashanna** [comment]
Thanks, it works now!

**Comment by rai-prashanna** [comment]
Thanks, it works now!

**Comment by sangkeon** [comment]
Resolved in 0.2.2
