### ISSUE TITLE
compilation error with java-opa-wasm:0.2.2 

### ISSUE THREAD

**Issue by rai-prashanna** [sangkeon/java-opa-wasm#9]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project performanceTesting: Compilation failure

cannot access io.github.kawamuray.wasmtime.Disposable
[ERROR]   class file for io.github.kawamuray.wasmtime.Disposable not found

I would appreciate your help. 
Thanks!

**Comment by rai-prashanna** [comment]
I don't get compilation error after adding following dependency in pom.xml 
        <dependency>
          <groupId>io.github.kawamuray.wasmtime</groupId>
          <artifactId>wasmtime-java</artifactId>
          <version>0.14.0</version>
        </dependency>
        
however, the following lines of code never get executed.       
om.loadEntrypoints();
String  decision=om.evaluate(inputJson,"authz/policy/allow");

**Comment by sangkeon** [comment]
call om.loadEntrypoints() before evaluate() no more required.

If you want to check multiple entrypoints correctly loaded, check returned value of om.getEntrypoints().

Code:    System.out.println(om.getEntrypoints());
Result: {opa/wasm/test/allowed=0}

Check "authz/policy/allow" exists.

**Comment by sangkeon** [comment]
I tested multiple entrypoints, there's no problem.

**Comment by rai-prashanna** [comment]
@sangkeon 
This is the compilation error I get in my environment. 
Tested on OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode), OPA 0.52.0 version 
![error](https://github.com/sangkeon/java-opa-wasm/assets/21035884/e8b565d1-dae6-4998-9658-e57c1ad36a66)
I created a repo that does interaction with wasm binary using opa-java-wasm library in Java. 
link to the GitHub repo is [https://github.com/rai-prashanna/test-opa-java-wasm](url)

**Comment by sangkeon** [comment]
It's maven dependency scope issue.

Fixed in 0.2.3.

**Comment by rai-prashanna** [comment]
@sangkeon 
Now, i don't get any compilation error but executions skip from the initialization of OPAModule without executing evaluate method. 
When I added breakpoints, I could see that execution is happening till line 77 of OPAModule.class but after that execution exits from there as can be seen in this pictures also. 
So execution happens never to this line om.evaluate(inputJson,"authz/policy/allow");
![image](https://github.com/sangkeon/java-opa-wasm/assets/21035884/db63e70d-68c1-4102-892c-520930f94fc1)
second picture of execution is as follows 
![image](https://github.com/sangkeon/java-opa-wasm/assets/21035884/51716585-a8d5-4d4e-adb4-e94f239d9590)

My wasm binary is in this bundle

 
[bundle.tar.gz](https://github.com/sangkeon/java-opa-wasm/files/11533166/bundle.tar.gz)

**Comment by sangkeon** [comment]
![result](https://github.com/sangkeon/java-opa-wasm/assets/4760376/f0d50867-0c1c-4d7c-8907-fcee4fc35782)
In my pc, your bundle works and returns result=[{"result":false}]

change your input string to "" and evaluate() called.

If it called and return result, it's input format issue.

**Comment by sangkeon** [comment]
Try to change JDK, json library and etc.

**Comment by rai-prashanna** [comment]
Thanks for your prompt response. 
I wrote code like you did in picture.
I experiment with JDK 8 and JDK 11. None of them work.  
Now, I get a different error. 
![image](https://github.com/sangkeon/java-opa-wasm/assets/21035884/9f19f1d6-e210-43fb-9b6b-79129b593f7a)
My glibc version is 
![image](https://github.com/sangkeon/java-opa-wasm/assets/21035884/a6ab4b28-6397-40db-8c44-8018b08d8d1c)

My os version is VERSION= ubuntu "20.04.6 LTS (Focal Fossa)"

**Comment by sangkeon** [comment]
Use java-opa-wasm 0.2.3_glibc2.31 version. (just downgraded wasmtime-java 0.14.0 to 0.13.0)

https://central.sonatype.com/artifact/io.github.sangkeon/java-opa-wasm/0.2.3_glibc2.31/versions

**Comment by rai-prashanna** [comment]
Thanks!
Now, it works!
